
name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove old build cache
        run: |
          rm -rf build

      - name: Install dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            qt6-base-dev \
            qt6-svg-dev \
            libqt6charts6-dev \
            libyaml-cpp-dev \
            xprintidle \
            brightnessctl \
            cmake \
            ninja-build

      - name: Configure CMake
        run: |
          cmake \
            -S . \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DHRM_FETCH_YAML_CPP=ON

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Run Tests
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          ctest \
            --test-dir build \
            --output-on-failure \
            --parallel
