name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-svg-dev libqt6charts6-dev xprintidle brightnessctl cmake ninja-build

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DHRM_FETCH_YAML_CPP=ON

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
